// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

part 'bridge_generated.freezed.dart';

abstract class Native {
  Future<String> sayHello({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSayHelloConstMeta;

  void update({required double dt, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kUpdateConstMeta;

  RawIndex createEntity({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateEntityConstMeta;

  void dropEntity({required RawIndex index, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDropEntityConstMeta;

  void entitySetPosition(
      {required RawIndex index,
      required double x,
      required double y,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEntitySetPositionConstMeta;

  void entitiesSetPositionRaw(
      {required Uint8List indices, required Uint8List positions, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEntitiesSetPositionRawConstMeta;

  void entitySetOrigin(
      {required RawIndex index,
      required bool relative,
      required double x,
      required double y,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEntitySetOriginConstMeta;

  void entitySetRotation(
      {required RawIndex index, required double rotation, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEntitySetRotationConstMeta;

  void entitiesSetRotationRaw(
      {required Uint8List indices, required Uint8List rotations, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEntitiesSetRotationRawConstMeta;

  void entitySetShape(
      {required RawIndex index, required Shape shape, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEntitySetShapeConstMeta;

  List<RawIndex> queryAabb(
      {required double x,
      required double y,
      required double width,
      required double height,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kQueryAabbConstMeta;

  Uint8List queryAabbRaw(
      {required double x,
      required double y,
      required double width,
      required double height,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kQueryAabbRawConstMeta;
}

class RawIndex {
  final int field0;
  final int field1;

  const RawIndex({
    required this.field0,
    required this.field1,
  });
}

@freezed
class Shape with _$Shape {
  const factory Shape.ball({
    required double radius,
  }) = Shape_Ball;
  const factory Shape.compound({
    required List<Shape> children,
    required List<ShapeTransform> transforms,
  }) = Shape_Compound;
}

class ShapeTransform {
  final double positionX;
  final double positionY;
  final double rotation;
  final double absoluteOriginX;
  final double absoluteOriginY;

  const ShapeTransform({
    required this.positionX,
    required this.positionY,
    required this.rotation,
    required this.absoluteOriginX,
    required this.absoluteOriginY,
  });
}

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<String> sayHello({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_say_hello(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kSayHelloConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSayHelloConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "say_hello",
        argNames: [],
      );

  void update({required double dt, dynamic hint}) {
    var arg0 = api2wire_f64(dt);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_update(arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kUpdateConstMeta,
      argValues: [dt],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kUpdateConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "update",
        argNames: ["dt"],
      );

  RawIndex createEntity({dynamic hint}) {
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_create_entity(),
      parseSuccessData: _wire2api_raw_index,
      constMeta: kCreateEntityConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCreateEntityConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "create_entity",
        argNames: [],
      );

  void dropEntity({required RawIndex index, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_raw_index(index);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_drop_entity(arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kDropEntityConstMeta,
      argValues: [index],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDropEntityConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "drop_entity",
        argNames: ["index"],
      );

  void entitySetPosition(
      {required RawIndex index,
      required double x,
      required double y,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_raw_index(index);
    var arg1 = api2wire_f64(x);
    var arg2 = api2wire_f64(y);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_entity_set_position(arg0, arg1, arg2),
      parseSuccessData: _wire2api_unit,
      constMeta: kEntitySetPositionConstMeta,
      argValues: [index, x, y],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEntitySetPositionConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "entity_set_position",
        argNames: ["index", "x", "y"],
      );

  void entitiesSetPositionRaw(
      {required Uint8List indices,
      required Uint8List positions,
      dynamic hint}) {
    var arg0 = _platform.api2wire_ZeroCopyBuffer_Uint8List(indices);
    var arg1 = _platform.api2wire_ZeroCopyBuffer_Uint8List(positions);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_entities_set_position_raw(arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kEntitiesSetPositionRawConstMeta,
      argValues: [indices, positions],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEntitiesSetPositionRawConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "entities_set_position_raw",
        argNames: ["indices", "positions"],
      );

  void entitySetOrigin(
      {required RawIndex index,
      required bool relative,
      required double x,
      required double y,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_raw_index(index);
    var arg1 = relative;
    var arg2 = api2wire_f64(x);
    var arg3 = api2wire_f64(y);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () =>
          _platform.inner.wire_entity_set_origin(arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_unit,
      constMeta: kEntitySetOriginConstMeta,
      argValues: [index, relative, x, y],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEntitySetOriginConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "entity_set_origin",
        argNames: ["index", "relative", "x", "y"],
      );

  void entitySetRotation(
      {required RawIndex index, required double rotation, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_raw_index(index);
    var arg1 = api2wire_f64(rotation);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_entity_set_rotation(arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kEntitySetRotationConstMeta,
      argValues: [index, rotation],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEntitySetRotationConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "entity_set_rotation",
        argNames: ["index", "rotation"],
      );

  void entitiesSetRotationRaw(
      {required Uint8List indices,
      required Uint8List rotations,
      dynamic hint}) {
    var arg0 = _platform.api2wire_ZeroCopyBuffer_Uint8List(indices);
    var arg1 = _platform.api2wire_ZeroCopyBuffer_Uint8List(rotations);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_entities_set_rotation_raw(arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kEntitiesSetRotationRawConstMeta,
      argValues: [indices, rotations],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEntitiesSetRotationRawConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "entities_set_rotation_raw",
        argNames: ["indices", "rotations"],
      );

  void entitySetShape(
      {required RawIndex index, required Shape shape, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_raw_index(index);
    var arg1 = _platform.api2wire_box_autoadd_shape(shape);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_entity_set_shape(arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kEntitySetShapeConstMeta,
      argValues: [index, shape],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEntitySetShapeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "entity_set_shape",
        argNames: ["index", "shape"],
      );

  List<RawIndex> queryAabb(
      {required double x,
      required double y,
      required double width,
      required double height,
      dynamic hint}) {
    var arg0 = api2wire_f64(x);
    var arg1 = api2wire_f64(y);
    var arg2 = api2wire_f64(width);
    var arg3 = api2wire_f64(height);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_query_aabb(arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_list_raw_index,
      constMeta: kQueryAabbConstMeta,
      argValues: [x, y, width, height],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueryAabbConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "query_aabb",
        argNames: ["x", "y", "width", "height"],
      );

  Uint8List queryAabbRaw(
      {required double x,
      required double y,
      required double width,
      required double height,
      dynamic hint}) {
    var arg0 = api2wire_f64(x);
    var arg1 = api2wire_f64(y);
    var arg2 = api2wire_f64(width);
    var arg3 = api2wire_f64(height);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () =>
          _platform.inner.wire_query_aabb_raw(arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_ZeroCopyBuffer_Uint8List,
      constMeta: kQueryAabbRawConstMeta,
      argValues: [x, y, width, height],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kQueryAabbRawConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "query_aabb_raw",
        argNames: ["x", "y", "width", "height"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  Uint8List _wire2api_ZeroCopyBuffer_Uint8List(dynamic raw) {
    return raw as Uint8List;
  }

  List<RawIndex> _wire2api_list_raw_index(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_raw_index).toList();
  }

  RawIndex _wire2api_raw_index(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RawIndex(
      field0: _wire2api_usize(arr[0]),
      field1: _wire2api_u64(arr[1]),
    );
  }

  int _wire2api_u64(dynamic raw) {
    return castInt(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }

  int _wire2api_usize(dynamic raw) {
    return castInt(raw);
  }
}

// Section: api2wire

@protected
bool api2wire_bool(bool raw) {
  return raw;
}

@protected
double api2wire_f64(double raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

@protected
int api2wire_usize(int raw) {
  return raw;
}
// Section: finalizer
