// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.75.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class NativePlatform extends FlutterRustBridgeBase<NativeWire>
    with FlutterRustBridgeSetupMixin {
  NativePlatform(FutureOr<WasmModule> dylib) : super(NativeWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  List<dynamic> api2wire_box_autoadd_generational_index(GenerationalIndex raw) {
    return api2wire_generational_index(raw);
  }

  @protected
  List<dynamic> api2wire_box_autoadd_shape(Shape raw) {
    return api2wire_shape(raw);
  }

  @protected
  Float32List api2wire_float_32_list(Float32List raw) {
    return raw;
  }

  @protected
  List<dynamic> api2wire_generational_index(GenerationalIndex raw) {
    return [api2wire_usize(raw.field0), api2wire_u64(raw.field1)];
  }

  @protected
  Int32List api2wire_int_32_list(Int32List raw) {
    return raw;
  }

  @protected
  List<dynamic> api2wire_list_shape(List<Shape> raw) {
    return raw.map(api2wire_shape).toList();
  }

  @protected
  List<dynamic> api2wire_list_shape_transform(List<ShapeTransform> raw) {
    return raw.map(api2wire_shape_transform).toList();
  }

  @protected
  List<dynamic> api2wire_shape(Shape raw) {
    if (raw is Shape_Ball) {
      return [0, api2wire_f32(raw.radius)];
    }
    if (raw is Shape_Compound) {
      return [
        1,
        api2wire_list_shape(raw.children),
        api2wire_list_shape_transform(raw.transforms)
      ];
    }

    throw Exception('unreachable');
  }

  @protected
  List<dynamic> api2wire_shape_transform(ShapeTransform raw) {
    return [
      api2wire_f32(raw.positionX),
      api2wire_f32(raw.positionY),
      api2wire_f32(raw.rotation),
      api2wire_f32(raw.absoluteOriginX),
      api2wire_f32(raw.absoluteOriginY)
    ];
  }

  @protected
  Object api2wire_u64(int raw) {
    return castNativeBigInt(raw);
  }

  @protected
  Uint16List api2wire_uint_16_list(Uint16List raw) {
    return raw;
  }

  @protected
  Uint32List api2wire_uint_32_list(Uint32List raw) {
    return raw;
  }

// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external NativeWasmModule get wasmModule;

@JS()
@anonymous
class NativeWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external NativeWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_say_hello(NativePortType port_);

  external dynamic /* void */ wire_screen_size_changed(
      double width, double height);

  external dynamic /* void */ wire_update(double dt);

  external dynamic /* List<dynamic> */ wire_create_entity();

  external dynamic /* void */ wire_drop_entity(List<dynamic> index);

  external dynamic /* void */ wire_entities_set_transform_raw(
      Uint32List indices,
      Float32List positions,
      Float32List origins,
      Float32List rotations,
      Float32List scales);

  external dynamic /* void */ wire_entities_set_position_raw(
      Uint32List indices, Float32List positions);

  external dynamic /* void */ wire_entities_set_origin_raw(
      Uint32List indices, Float32List origins);

  external dynamic /* void */ wire_entities_set_rotation_raw(
      Uint32List indices, Float32List rotations);

  external dynamic /* void */ wire_entities_set_scale_raw(
      Uint32List indices, Float32List scales);

  external dynamic /* List<dynamic> */ wire_query_aabb(
      double x, double y, double width, double height);

  external dynamic /* Uint32List */ wire_query_aabb_raw(
      double x, double y, double width, double height);

  external dynamic /* void */ wire_entity_set_vertices_raw(
      List<dynamic> index, Float32List vertices);

  external dynamic /* void */ wire_entity_set_tex_coords_raw(
      List<dynamic> index, Float32List tex_coords);

  external dynamic /* void */ wire_entity_set_indices_raw(
      List<dynamic> index, Uint16List indices);

  external dynamic /* void */ wire_entities_set_priority_raw(
      Uint32List indices, Int32List priorities);

  external dynamic /* void */ wire_entity_set_shape(
      List<dynamic> index, List<dynamic> shape);

  external dynamic /* void */ wire_entity_set_color(
      List<dynamic> index, int color);

  external dynamic /* Object */ wire_batches_count();

  external dynamic /* Float32List */ wire_vertices(int batch_index);

  external dynamic /* Float32List */ wire_tex_coords(int batch_index);

  external dynamic /* Uint16List */ wire_indices(int batch_index);

  external dynamic /* Int32List */ wire_colors(int batch_index);
}

// Section: WASM wire connector

class NativeWire extends FlutterRustBridgeWasmWireBase<NativeWasmModule> {
  NativeWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<NativeWasmModule>(module));

  void wire_say_hello(NativePortType port_) => wasmModule.wire_say_hello(port_);

  dynamic /* void */ wire_screen_size_changed(double width, double height) =>
      wasmModule.wire_screen_size_changed(width, height);

  dynamic /* void */ wire_update(double dt) => wasmModule.wire_update(dt);

  dynamic /* List<dynamic> */ wire_create_entity() =>
      wasmModule.wire_create_entity();

  dynamic /* void */ wire_drop_entity(List<dynamic> index) =>
      wasmModule.wire_drop_entity(index);

  dynamic /* void */ wire_entities_set_transform_raw(
          Uint32List indices,
          Float32List positions,
          Float32List origins,
          Float32List rotations,
          Float32List scales) =>
      wasmModule.wire_entities_set_transform_raw(
          indices, positions, origins, rotations, scales);

  dynamic /* void */ wire_entities_set_position_raw(
          Uint32List indices, Float32List positions) =>
      wasmModule.wire_entities_set_position_raw(indices, positions);

  dynamic /* void */ wire_entities_set_origin_raw(
          Uint32List indices, Float32List origins) =>
      wasmModule.wire_entities_set_origin_raw(indices, origins);

  dynamic /* void */ wire_entities_set_rotation_raw(
          Uint32List indices, Float32List rotations) =>
      wasmModule.wire_entities_set_rotation_raw(indices, rotations);

  dynamic /* void */ wire_entities_set_scale_raw(
          Uint32List indices, Float32List scales) =>
      wasmModule.wire_entities_set_scale_raw(indices, scales);

  dynamic /* List<dynamic> */ wire_query_aabb(
          double x, double y, double width, double height) =>
      wasmModule.wire_query_aabb(x, y, width, height);

  dynamic /* Uint32List */ wire_query_aabb_raw(
          double x, double y, double width, double height) =>
      wasmModule.wire_query_aabb_raw(x, y, width, height);

  dynamic /* void */ wire_entity_set_vertices_raw(
          List<dynamic> index, Float32List vertices) =>
      wasmModule.wire_entity_set_vertices_raw(index, vertices);

  dynamic /* void */ wire_entity_set_tex_coords_raw(
          List<dynamic> index, Float32List tex_coords) =>
      wasmModule.wire_entity_set_tex_coords_raw(index, tex_coords);

  dynamic /* void */ wire_entity_set_indices_raw(
          List<dynamic> index, Uint16List indices) =>
      wasmModule.wire_entity_set_indices_raw(index, indices);

  dynamic /* void */ wire_entities_set_priority_raw(
          Uint32List indices, Int32List priorities) =>
      wasmModule.wire_entities_set_priority_raw(indices, priorities);

  dynamic /* void */ wire_entity_set_shape(
          List<dynamic> index, List<dynamic> shape) =>
      wasmModule.wire_entity_set_shape(index, shape);

  dynamic /* void */ wire_entity_set_color(List<dynamic> index, int color) =>
      wasmModule.wire_entity_set_color(index, color);

  dynamic /* Object */ wire_batches_count() => wasmModule.wire_batches_count();

  dynamic /* Float32List */ wire_vertices(int batch_index) =>
      wasmModule.wire_vertices(batch_index);

  dynamic /* Float32List */ wire_tex_coords(int batch_index) =>
      wasmModule.wire_tex_coords(batch_index);

  dynamic /* Uint16List */ wire_indices(int batch_index) =>
      wasmModule.wire_indices(batch_index);

  dynamic /* Int32List */ wire_colors(int batch_index) =>
      wasmModule.wire_colors(batch_index);
}
