name: dashmark_pure
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vector_math: ^2.1.4
  flutter_rust_bridge: ^1.69.0
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  freezed: ^2.3.2
  ffigen: ^7.2.7
flutter:
  uses-material-design: true
  assets:
   - assets/images/
  shaders:
   - shaders/sprite.glsl
