// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.69.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class NativePlatform extends FlutterRustBridgeBase<NativeWire>
    with FlutterRustBridgeSetupMixin {
  NativePlatform(FutureOr<WasmModule> dylib) : super(NativeWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  List<dynamic> api2wire_box_autoadd_raw_index(RawIndex raw) {
    return api2wire_raw_index(raw);
  }

  @protected
  List<dynamic> api2wire_box_autoadd_shape(Shape raw) {
    return api2wire_shape(raw);
  }

  @protected
  List<dynamic> api2wire_box_shape(Shape raw) {
    return api2wire_shape(raw);
  }

  @protected
  List<dynamic> api2wire_list_box_shape(List<Shape> raw) {
    return raw.map(api2wire_box_shape).toList();
  }

  @protected
  List<dynamic> api2wire_list_raw_index(List<RawIndex> raw) {
    return raw.map(api2wire_raw_index).toList();
  }

  @protected
  List<dynamic> api2wire_list_shape_transform(List<ShapeTransform> raw) {
    return raw.map(api2wire_shape_transform).toList();
  }

  @protected
  List<dynamic> api2wire_raw_index(RawIndex raw) {
    return [api2wire_usize(raw.field0), api2wire_u64(raw.field1)];
  }

  @protected
  List<dynamic> api2wire_shape(Shape raw) {
    if (raw is Shape_Ball) {
      return [0, api2wire_f64(raw.radius)];
    }
    if (raw is Shape_Compound) {
      return [
        1,
        api2wire_list_box_shape(raw.children),
        api2wire_list_shape_transform(raw.transforms)
      ];
    }

    throw Exception('unreachable');
  }

  @protected
  List<dynamic> api2wire_shape_transform(ShapeTransform raw) {
    return [
      api2wire_f64(raw.positionX),
      api2wire_f64(raw.positionY),
      api2wire_f64(raw.rotation),
      api2wire_f64(raw.absoluteOriginX),
      api2wire_f64(raw.absoluteOriginY)
    ];
  }

  @protected
  Object api2wire_u64(int raw) {
    return castNativeBigInt(raw);
  }

// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external NativeWasmModule get wasmModule;

@JS()
@anonymous
class NativeWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external NativeWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_say_hello(NativePortType port_);

  external dynamic /* List<dynamic> */ wire_create_entity();

  external dynamic /* void */ wire_drop_entity(List<dynamic> index);

  external dynamic /* void */ wire_entity_set_position(
      List<dynamic> index, double x, double y);

  external dynamic /* void */ wire_entity_set_origin(
      List<dynamic> index, bool relative, double x, double y);

  external dynamic /* void */ wire_entity_set_rotation(
      List<dynamic> index, double rotation);

  external dynamic /* void */ wire_entity_set_shape(
      List<dynamic> index, List<dynamic> shape);

  external dynamic /* List<dynamic> */ wire_create_bvh();

  external dynamic /* void */ wire_drop_bvh(List<dynamic> index);

  external dynamic /* void */ wire_bvh_clear_and_rebuild(
      List<dynamic> index, List<dynamic> entities, double dilation_factor);

  external dynamic /* List<dynamic> */ wire_bvh_flatten(List<dynamic> index);
}

// Section: WASM wire connector

class NativeWire extends FlutterRustBridgeWasmWireBase<NativeWasmModule> {
  NativeWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<NativeWasmModule>(module));

  void wire_say_hello(NativePortType port_) => wasmModule.wire_say_hello(port_);

  dynamic /* List<dynamic> */ wire_create_entity() =>
      wasmModule.wire_create_entity();

  dynamic /* void */ wire_drop_entity(List<dynamic> index) =>
      wasmModule.wire_drop_entity(index);

  dynamic /* void */ wire_entity_set_position(
          List<dynamic> index, double x, double y) =>
      wasmModule.wire_entity_set_position(index, x, y);

  dynamic /* void */ wire_entity_set_origin(
          List<dynamic> index, bool relative, double x, double y) =>
      wasmModule.wire_entity_set_origin(index, relative, x, y);

  dynamic /* void */ wire_entity_set_rotation(
          List<dynamic> index, double rotation) =>
      wasmModule.wire_entity_set_rotation(index, rotation);

  dynamic /* void */ wire_entity_set_shape(
          List<dynamic> index, List<dynamic> shape) =>
      wasmModule.wire_entity_set_shape(index, shape);

  dynamic /* List<dynamic> */ wire_create_bvh() => wasmModule.wire_create_bvh();

  dynamic /* void */ wire_drop_bvh(List<dynamic> index) =>
      wasmModule.wire_drop_bvh(index);

  dynamic /* void */ wire_bvh_clear_and_rebuild(List<dynamic> index,
          List<dynamic> entities, double dilation_factor) =>
      wasmModule.wire_bvh_clear_and_rebuild(index, entities, dilation_factor);

  dynamic /* List<dynamic> */ wire_bvh_flatten(List<dynamic> index) =>
      wasmModule.wire_bvh_flatten(index);
}
