// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.69.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

abstract class Native {
  Future<String> sayHelloAsync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSayHelloAsyncConstMeta;

  Future<Uint64List> mortonCodesAsync(
      {required Float64List xs, required Float64List ys, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMortonCodesAsyncConstMeta;

  Uint64List mortonCodes(
      {required Float64List xs, required Float64List ys, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMortonCodesConstMeta;
}

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<String> sayHelloAsync({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_say_hello_async(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kSayHelloAsyncConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSayHelloAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "say_hello_async",
        argNames: [],
      );

  Future<Uint64List> mortonCodesAsync(
      {required Float64List xs, required Float64List ys, dynamic hint}) {
    var arg0 = _platform.api2wire_float_64_list(xs);
    var arg1 = _platform.api2wire_float_64_list(ys);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_morton_codes_async(port_, arg0, arg1),
      parseSuccessData: _wire2api_uint_64_list,
      constMeta: kMortonCodesAsyncConstMeta,
      argValues: [xs, ys],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMortonCodesAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "morton_codes_async",
        argNames: ["xs", "ys"],
      );

  Uint64List mortonCodes(
      {required Float64List xs, required Float64List ys, dynamic hint}) {
    var arg0 = _platform.api2wire_float_64_list(xs);
    var arg1 = _platform.api2wire_float_64_list(ys);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_morton_codes(arg0, arg1),
      parseSuccessData: _wire2api_uint_64_list,
      constMeta: kMortonCodesConstMeta,
      argValues: [xs, ys],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMortonCodesConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "morton_codes",
        argNames: ["xs", "ys"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_u64(dynamic raw) {
    return castInt(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint64List _wire2api_uint_64_list(dynamic raw) {
    return Uint64List.from(raw);
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
double api2wire_f64(double raw) {
  return raw;
}

// Section: finalizer
