// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.69.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class NativePlatform extends FlutterRustBridgeBase<NativeWire>
    with FlutterRustBridgeSetupMixin {
  NativePlatform(FutureOr<WasmModule> dylib) : super(NativeWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  List<dynamic> api2wire_box_autoadd_index(Index raw) {
    return api2wire_index(raw);
  }

  @protected
  Float64List api2wire_f64_array_2(F64Array2 raw) {
    return Float64List.fromList(raw);
  }

  @protected
  Float64List api2wire_float_64_list(Float64List raw) {
    return raw;
  }

  @protected
  List<dynamic> api2wire_index(Index raw) {
    return [api2wire_usize(raw.index), api2wire_u64(raw.generation)];
  }

  @protected
  List<dynamic> api2wire_list_index(List<Index> raw) {
    return raw.map(api2wire_index).toList();
  }

  @protected
  Object api2wire_u64(int raw) {
    return castNativeBigInt(raw);
  }

// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external NativeWasmModule get wasmModule;

@JS()
@anonymous
class NativeWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external NativeWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_say_hello_async(NativePortType port_);

  external dynamic /* void */ wire_morton_codes_async(
      NativePortType port_, Float64List xs, Float64List ys);

  external dynamic /* Object /* BigInt64Array */ */ wire_morton_codes(
      Float64List xs, Float64List ys);

  external dynamic /* List<dynamic> */ wire_aabb_new(
      double min_x, double min_y, double max_x, double max_y);

  external dynamic /* List<dynamic> */ wire_aabb_new_bulk(Float64List min_xs,
      Float64List min_ys, Float64List max_xs, Float64List max_ys);

  external dynamic /* Uint8List */ wire_aabb_drop_bulk(List<dynamic> aabb_ids);

  external dynamic /* Float64List */ wire_aabb_min(List<dynamic> aabb_id);

  external dynamic /* Float64List */ wire_aabb_max(List<dynamic> aabb_id);

  external dynamic /* Float64List */ wire_aabb_size(List<dynamic> aabb_id);

  external dynamic /* Float64List */ wire_aabb_center(List<dynamic> aabb_id);

  external dynamic /* bool */ wire_aabb_intersects_aabb(
      List<dynamic> aabb_left_id, List<dynamic> aabb_right_id);

  external dynamic /* bool */ wire_aabb_contains_point(
      List<dynamic> aabb_id, Float64List point);

  external dynamic /* bool */ wire_aabb_contains_aabb(
      List<dynamic> aabb_left_id, List<dynamic> aabb_right_id);

  external dynamic /* List<dynamic> */ wire_aabb_merge(
      List<dynamic> aabb_left_id, List<dynamic> aabb_right_id);

  external dynamic /* void */ wire_aabb_merge_with(
      NativePortType port_, List<dynamic> aabb, List<dynamic> other);

  external dynamic /* List<dynamic> */ wire_bvh_new(List<dynamic> aabbs);

  external dynamic /* void */ wire_bvh_new_async(
      NativePortType port_, List<dynamic> aabbs);

  external dynamic /* bool */ wire_bvh_drop(List<dynamic> bvh_id);

  external dynamic /* List<dynamic> */ wire_bvh_flatten(List<dynamic> bvh_id);

  external dynamic /* void */ wire_bvh_flatten_async(
      NativePortType port_, List<dynamic> bvh_id);

  external dynamic /* Object */ wire_bvh_depth(List<dynamic> bvh_id);

  external dynamic /* void */ wire_bvh_depth_async(
      NativePortType port_, List<dynamic> bvh_id);

  external dynamic /* List<dynamic> */ wire_bvh_query_aabb_collisions(
      List<dynamic> bvh_id, List<dynamic> aabb_id);

  external dynamic /* List<dynamic> */ wire_bvh_query_aabb_collisions_min_max(
      List<dynamic> bvh_id,
      double min_x,
      double min_y,
      double max_x,
      double max_y);

  external dynamic /* List<dynamic> */ wire_bvh_query_point_collisions(
      List<dynamic> bvh_id, double x, double y);

  external dynamic /* String */ wire_bvh_print(List<dynamic> bvh_id);

  external dynamic /* void */ wire_bvh_print_async(
      NativePortType port_, List<dynamic> bvh_id);

  external dynamic /* double */ wire_bvh_overlap_ratio(List<dynamic> bvh_id);
}

// Section: WASM wire connector

class NativeWire extends FlutterRustBridgeWasmWireBase<NativeWasmModule> {
  NativeWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<NativeWasmModule>(module));

  void wire_say_hello_async(NativePortType port_) =>
      wasmModule.wire_say_hello_async(port_);

  void wire_morton_codes_async(
          NativePortType port_, Float64List xs, Float64List ys) =>
      wasmModule.wire_morton_codes_async(port_, xs, ys);

  dynamic /* Object /* BigInt64Array */ */ wire_morton_codes(
          Float64List xs, Float64List ys) =>
      wasmModule.wire_morton_codes(xs, ys);

  dynamic /* List<dynamic> */ wire_aabb_new(
          double min_x, double min_y, double max_x, double max_y) =>
      wasmModule.wire_aabb_new(min_x, min_y, max_x, max_y);

  dynamic /* List<dynamic> */ wire_aabb_new_bulk(Float64List min_xs,
          Float64List min_ys, Float64List max_xs, Float64List max_ys) =>
      wasmModule.wire_aabb_new_bulk(min_xs, min_ys, max_xs, max_ys);

  dynamic /* Uint8List */ wire_aabb_drop_bulk(List<dynamic> aabb_ids) =>
      wasmModule.wire_aabb_drop_bulk(aabb_ids);

  dynamic /* Float64List */ wire_aabb_min(List<dynamic> aabb_id) =>
      wasmModule.wire_aabb_min(aabb_id);

  dynamic /* Float64List */ wire_aabb_max(List<dynamic> aabb_id) =>
      wasmModule.wire_aabb_max(aabb_id);

  dynamic /* Float64List */ wire_aabb_size(List<dynamic> aabb_id) =>
      wasmModule.wire_aabb_size(aabb_id);

  dynamic /* Float64List */ wire_aabb_center(List<dynamic> aabb_id) =>
      wasmModule.wire_aabb_center(aabb_id);

  dynamic /* bool */ wire_aabb_intersects_aabb(
          List<dynamic> aabb_left_id, List<dynamic> aabb_right_id) =>
      wasmModule.wire_aabb_intersects_aabb(aabb_left_id, aabb_right_id);

  dynamic /* bool */ wire_aabb_contains_point(
          List<dynamic> aabb_id, Float64List point) =>
      wasmModule.wire_aabb_contains_point(aabb_id, point);

  dynamic /* bool */ wire_aabb_contains_aabb(
          List<dynamic> aabb_left_id, List<dynamic> aabb_right_id) =>
      wasmModule.wire_aabb_contains_aabb(aabb_left_id, aabb_right_id);

  dynamic /* List<dynamic> */ wire_aabb_merge(
          List<dynamic> aabb_left_id, List<dynamic> aabb_right_id) =>
      wasmModule.wire_aabb_merge(aabb_left_id, aabb_right_id);

  void wire_aabb_merge_with(
          NativePortType port_, List<dynamic> aabb, List<dynamic> other) =>
      wasmModule.wire_aabb_merge_with(port_, aabb, other);

  dynamic /* List<dynamic> */ wire_bvh_new(List<dynamic> aabbs) =>
      wasmModule.wire_bvh_new(aabbs);

  void wire_bvh_new_async(NativePortType port_, List<dynamic> aabbs) =>
      wasmModule.wire_bvh_new_async(port_, aabbs);

  dynamic /* bool */ wire_bvh_drop(List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_drop(bvh_id);

  dynamic /* List<dynamic> */ wire_bvh_flatten(List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_flatten(bvh_id);

  void wire_bvh_flatten_async(NativePortType port_, List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_flatten_async(port_, bvh_id);

  dynamic /* Object */ wire_bvh_depth(List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_depth(bvh_id);

  void wire_bvh_depth_async(NativePortType port_, List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_depth_async(port_, bvh_id);

  dynamic /* List<dynamic> */ wire_bvh_query_aabb_collisions(
          List<dynamic> bvh_id, List<dynamic> aabb_id) =>
      wasmModule.wire_bvh_query_aabb_collisions(bvh_id, aabb_id);

  dynamic /* List<dynamic> */ wire_bvh_query_aabb_collisions_min_max(
          List<dynamic> bvh_id,
          double min_x,
          double min_y,
          double max_x,
          double max_y) =>
      wasmModule.wire_bvh_query_aabb_collisions_min_max(
          bvh_id, min_x, min_y, max_x, max_y);

  dynamic /* List<dynamic> */ wire_bvh_query_point_collisions(
          List<dynamic> bvh_id, double x, double y) =>
      wasmModule.wire_bvh_query_point_collisions(bvh_id, x, y);

  dynamic /* String */ wire_bvh_print(List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_print(bvh_id);

  void wire_bvh_print_async(NativePortType port_, List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_print_async(port_, bvh_id);

  dynamic /* double */ wire_bvh_overlap_ratio(List<dynamic> bvh_id) =>
      wasmModule.wire_bvh_overlap_ratio(bvh_id);
}
