// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.69.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class NativePlatform extends FlutterRustBridgeBase<NativeWire>
    with FlutterRustBridgeSetupMixin {
  NativePlatform(FutureOr<WasmModule> dylib) : super(NativeWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  Object api2wire_RwLockAabb(RwLockAabb raw) {
    return raw.shareOrMove();
  }

  @protected
  Float64List api2wire_float_64_list(Float64List raw) {
    return raw;
  }

  @protected
  List<dynamic> api2wire_list_RwLockAabb(List<RwLockAabb> raw) {
    return raw.map(api2wire_RwLockAabb).toList();
  }
// Section: finalizer

  late final Finalizer<PlatformPointer> _RwLockAabbFinalizer =
      Finalizer<PlatformPointer>(inner.drop_opaque_RwLockAabb);
  Finalizer<PlatformPointer> get RwLockAabbFinalizer => _RwLockAabbFinalizer;
  late final Finalizer<PlatformPointer> _RwLockBvhFinalizer =
      Finalizer<PlatformPointer>(inner.drop_opaque_RwLockBvh);
  Finalizer<PlatformPointer> get RwLockBvhFinalizer => _RwLockBvhFinalizer;
}

// Section: WASM wire module

@JS('wasm_bindgen')
external NativeWasmModule get wasmModule;

@JS()
@anonymous
class NativeWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external NativeWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_say_hello_async(NativePortType port_);

  external dynamic /* void */ wire_morton_codes_async(
      NativePortType port_, Float64List xs, Float64List ys);

  external dynamic /* Object /* BigInt64Array */ */ wire_morton_codes(
      Float64List xs, Float64List ys);

  external dynamic /* Object */ wire_aabb_new(
      double min_x, double min_y, double max_x, double max_y);

  external dynamic /* List<dynamic> */ wire_aabb_new_bulk(Float64List min_xs,
      Float64List min_ys, Float64List max_xs, Float64List max_ys);

  external dynamic /* Object */ wire_aabb_new_bulk_benchmark(Float64List min_xs,
      Float64List min_ys, Float64List max_xs, Float64List max_ys);

  external dynamic /* Float64List */ wire_aabb_min(Object aabb);

  external dynamic /* Float64List */ wire_aabb_max(Object aabb);

  external dynamic /* Float64List */ wire_aabb_size(Object aabb);

  external dynamic /* Float64List */ wire_aabb_center(Object aabb);

  external dynamic /* bool */ wire_aabb_intersects(
      Object aabb_left, Object aabb_right);

  external dynamic /* bool */ wire_aabb_contains(
      Object aabb, Float64List point);

  external dynamic /* bool */ wire_aabb_contains_aabb(
      Object aabb_left, Object aabb_right);

  external dynamic /* Object */ wire_aabb_merge(
      Object aabb_left, Object aabb_right);

  external dynamic /* Object */ wire_aabb_merge_with(Object aabb, Object other);

  external dynamic /* Object */ wire_bvh_new(List<dynamic> aabbs);

  external dynamic /* void */ wire_bvh_new_async(
      NativePortType port_, List<dynamic> aabbs);

  external dynamic /*  */ drop_opaque_RwLockAabb(ptr);

  external int /* *const c_void */ share_opaque_RwLockAabb(ptr);

  external dynamic /*  */ drop_opaque_RwLockBvh(ptr);

  external int /* *const c_void */ share_opaque_RwLockBvh(ptr);
}

// Section: WASM wire connector

class NativeWire extends FlutterRustBridgeWasmWireBase<NativeWasmModule> {
  NativeWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<NativeWasmModule>(module));

  void wire_say_hello_async(NativePortType port_) =>
      wasmModule.wire_say_hello_async(port_);

  void wire_morton_codes_async(
          NativePortType port_, Float64List xs, Float64List ys) =>
      wasmModule.wire_morton_codes_async(port_, xs, ys);

  dynamic /* Object /* BigInt64Array */ */ wire_morton_codes(
          Float64List xs, Float64List ys) =>
      wasmModule.wire_morton_codes(xs, ys);

  dynamic /* Object */ wire_aabb_new(
          double min_x, double min_y, double max_x, double max_y) =>
      wasmModule.wire_aabb_new(min_x, min_y, max_x, max_y);

  dynamic /* List<dynamic> */ wire_aabb_new_bulk(Float64List min_xs,
          Float64List min_ys, Float64List max_xs, Float64List max_ys) =>
      wasmModule.wire_aabb_new_bulk(min_xs, min_ys, max_xs, max_ys);

  dynamic /* Object */ wire_aabb_new_bulk_benchmark(Float64List min_xs,
          Float64List min_ys, Float64List max_xs, Float64List max_ys) =>
      wasmModule.wire_aabb_new_bulk_benchmark(min_xs, min_ys, max_xs, max_ys);

  dynamic /* Float64List */ wire_aabb_min(Object aabb) =>
      wasmModule.wire_aabb_min(aabb);

  dynamic /* Float64List */ wire_aabb_max(Object aabb) =>
      wasmModule.wire_aabb_max(aabb);

  dynamic /* Float64List */ wire_aabb_size(Object aabb) =>
      wasmModule.wire_aabb_size(aabb);

  dynamic /* Float64List */ wire_aabb_center(Object aabb) =>
      wasmModule.wire_aabb_center(aabb);

  dynamic /* bool */ wire_aabb_intersects(
          Object aabb_left, Object aabb_right) =>
      wasmModule.wire_aabb_intersects(aabb_left, aabb_right);

  dynamic /* bool */ wire_aabb_contains(Object aabb, Float64List point) =>
      wasmModule.wire_aabb_contains(aabb, point);

  dynamic /* bool */ wire_aabb_contains_aabb(
          Object aabb_left, Object aabb_right) =>
      wasmModule.wire_aabb_contains_aabb(aabb_left, aabb_right);

  dynamic /* Object */ wire_aabb_merge(Object aabb_left, Object aabb_right) =>
      wasmModule.wire_aabb_merge(aabb_left, aabb_right);

  dynamic /* Object */ wire_aabb_merge_with(Object aabb, Object other) =>
      wasmModule.wire_aabb_merge_with(aabb, other);

  dynamic /* Object */ wire_bvh_new(List<dynamic> aabbs) =>
      wasmModule.wire_bvh_new(aabbs);

  void wire_bvh_new_async(NativePortType port_, List<dynamic> aabbs) =>
      wasmModule.wire_bvh_new_async(port_, aabbs);

  dynamic /*  */ drop_opaque_RwLockAabb(ptr) =>
      wasmModule.drop_opaque_RwLockAabb(ptr);

  int /* *const c_void */ share_opaque_RwLockAabb(ptr) =>
      wasmModule.share_opaque_RwLockAabb(ptr);

  dynamic /*  */ drop_opaque_RwLockBvh(ptr) =>
      wasmModule.drop_opaque_RwLockBvh(ptr);

  int /* *const c_void */ share_opaque_RwLockBvh(ptr) =>
      wasmModule.share_opaque_RwLockBvh(ptr);
}
