// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.69.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

abstract class Native {
  Future<String> sayHelloAsync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSayHelloAsyncConstMeta;

  Future<Uint64List> mortonCodesAsync(
      {required Float64List xs, required Float64List ys, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMortonCodesAsyncConstMeta;

  Uint64List mortonCodes(
      {required Float64List xs, required Float64List ys, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMortonCodesConstMeta;

  int aabbNew(
      {required double minX,
      required double minY,
      required double maxX,
      required double maxY,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbNewConstMeta;

  Uint64List aabbNewBulk(
      {required Float64List minXs,
      required Float64List minYs,
      required Float64List maxXs,
      required Float64List maxYs,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbNewBulkConstMeta;

  void aabbDrop({required int aabbId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbDropConstMeta;

  Float64List aabbMin({required int aabbId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbMinConstMeta;

  Float64List aabbMax({required int aabbId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbMaxConstMeta;

  Float64List aabbSize({required int aabbId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbSizeConstMeta;

  Float64List aabbCenter({required int aabbId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbCenterConstMeta;

  bool aabbIntersectsAabb(
      {required int aabbLeftId, required int aabbRightId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbIntersectsAabbConstMeta;

  bool aabbContainsPoint(
      {required int aabbId, required Float64List point, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbContainsPointConstMeta;

  bool aabbContainsAabb(
      {required int aabbLeftId, required int aabbRightId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbContainsAabbConstMeta;

  int aabbMerge(
      {required int aabbLeftId, required int aabbRightId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbMergeConstMeta;

  Future<void> aabbMergeWith(
      {required int aabbId, required int otherId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAabbMergeWithConstMeta;

  int bvhNew({required Uint64List aabbs, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhNewConstMeta;

  Future<int> bvhNewAsync({required Uint64List aabbs, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhNewAsyncConstMeta;

  void bvhDrop({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhDropConstMeta;

  FlatBVH bvhFlatten({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhFlattenConstMeta;

  Future<FlatBVH> bvhFlattenAsync({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhFlattenAsyncConstMeta;

  int bvhDepth({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhDepthConstMeta;

  Future<int> bvhDepthAsync({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhDepthAsyncConstMeta;

  Uint64List bvhQueryAabbCollisions(
      {required int bvhId, required int aabbId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhQueryAabbCollisionsConstMeta;

  Uint64List bvhQueryPointCollisions(
      {required int bvhId, required double x, required double y, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhQueryPointCollisionsConstMeta;

  String bvhPrint({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhPrintConstMeta;

  Future<String> bvhPrintAsync({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhPrintAsyncConstMeta;

  double bvhOverlapRatio({required int bvhId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBvhOverlapRatioConstMeta;
}

class FlatBVH {
  final Float64List minX;
  final Float64List minY;
  final Float64List maxX;
  final Float64List maxY;
  final Uint64List depth;

  const FlatBVH({
    required this.minX,
    required this.minY,
    required this.maxX,
    required this.maxY,
    required this.depth,
  });
}

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<String> sayHelloAsync({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_say_hello_async(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kSayHelloAsyncConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSayHelloAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "say_hello_async",
        argNames: [],
      );

  Future<Uint64List> mortonCodesAsync(
      {required Float64List xs, required Float64List ys, dynamic hint}) {
    var arg0 = _platform.api2wire_float_64_list(xs);
    var arg1 = _platform.api2wire_float_64_list(ys);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_morton_codes_async(port_, arg0, arg1),
      parseSuccessData: _wire2api_uint_64_list,
      constMeta: kMortonCodesAsyncConstMeta,
      argValues: [xs, ys],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMortonCodesAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "morton_codes_async",
        argNames: ["xs", "ys"],
      );

  Uint64List mortonCodes(
      {required Float64List xs, required Float64List ys, dynamic hint}) {
    var arg0 = _platform.api2wire_float_64_list(xs);
    var arg1 = _platform.api2wire_float_64_list(ys);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_morton_codes(arg0, arg1),
      parseSuccessData: _wire2api_uint_64_list,
      constMeta: kMortonCodesConstMeta,
      argValues: [xs, ys],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMortonCodesConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "morton_codes",
        argNames: ["xs", "ys"],
      );

  int aabbNew(
      {required double minX,
      required double minY,
      required double maxX,
      required double maxY,
      dynamic hint}) {
    var arg0 = api2wire_f64(minX);
    var arg1 = api2wire_f64(minY);
    var arg2 = api2wire_f64(maxX);
    var arg3 = api2wire_f64(maxY);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_new(arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_u64,
      constMeta: kAabbNewConstMeta,
      argValues: [minX, minY, maxX, maxY],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbNewConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_new",
        argNames: ["minX", "minY", "maxX", "maxY"],
      );

  Uint64List aabbNewBulk(
      {required Float64List minXs,
      required Float64List minYs,
      required Float64List maxXs,
      required Float64List maxYs,
      dynamic hint}) {
    var arg0 = _platform.api2wire_float_64_list(minXs);
    var arg1 = _platform.api2wire_float_64_list(minYs);
    var arg2 = _platform.api2wire_float_64_list(maxXs);
    var arg3 = _platform.api2wire_float_64_list(maxYs);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_new_bulk(arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_uint_64_list,
      constMeta: kAabbNewBulkConstMeta,
      argValues: [minXs, minYs, maxXs, maxYs],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbNewBulkConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_new_bulk",
        argNames: ["minXs", "minYs", "maxXs", "maxYs"],
      );

  void aabbDrop({required int aabbId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_drop(arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kAabbDropConstMeta,
      argValues: [aabbId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbDropConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_drop",
        argNames: ["aabbId"],
      );

  Float64List aabbMin({required int aabbId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_min(arg0),
      parseSuccessData: _wire2api_float_64_list,
      constMeta: kAabbMinConstMeta,
      argValues: [aabbId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbMinConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_min",
        argNames: ["aabbId"],
      );

  Float64List aabbMax({required int aabbId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_max(arg0),
      parseSuccessData: _wire2api_float_64_list,
      constMeta: kAabbMaxConstMeta,
      argValues: [aabbId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbMaxConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_max",
        argNames: ["aabbId"],
      );

  Float64List aabbSize({required int aabbId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_size(arg0),
      parseSuccessData: _wire2api_float_64_list,
      constMeta: kAabbSizeConstMeta,
      argValues: [aabbId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbSizeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_size",
        argNames: ["aabbId"],
      );

  Float64List aabbCenter({required int aabbId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_center(arg0),
      parseSuccessData: _wire2api_float_64_list,
      constMeta: kAabbCenterConstMeta,
      argValues: [aabbId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbCenterConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_center",
        argNames: ["aabbId"],
      );

  bool aabbIntersectsAabb(
      {required int aabbLeftId, required int aabbRightId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbLeftId);
    var arg1 = _platform.api2wire_u64(aabbRightId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_intersects_aabb(arg0, arg1),
      parseSuccessData: _wire2api_bool,
      constMeta: kAabbIntersectsAabbConstMeta,
      argValues: [aabbLeftId, aabbRightId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbIntersectsAabbConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_intersects_aabb",
        argNames: ["aabbLeftId", "aabbRightId"],
      );

  bool aabbContainsPoint(
      {required int aabbId, required Float64List point, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbId);
    var arg1 = _platform.api2wire_float_64_list(point);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_contains_point(arg0, arg1),
      parseSuccessData: _wire2api_bool,
      constMeta: kAabbContainsPointConstMeta,
      argValues: [aabbId, point],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbContainsPointConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_contains_point",
        argNames: ["aabbId", "point"],
      );

  bool aabbContainsAabb(
      {required int aabbLeftId, required int aabbRightId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbLeftId);
    var arg1 = _platform.api2wire_u64(aabbRightId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_contains_aabb(arg0, arg1),
      parseSuccessData: _wire2api_bool,
      constMeta: kAabbContainsAabbConstMeta,
      argValues: [aabbLeftId, aabbRightId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbContainsAabbConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_contains_aabb",
        argNames: ["aabbLeftId", "aabbRightId"],
      );

  int aabbMerge(
      {required int aabbLeftId, required int aabbRightId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbLeftId);
    var arg1 = _platform.api2wire_u64(aabbRightId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_aabb_merge(arg0, arg1),
      parseSuccessData: _wire2api_u64,
      constMeta: kAabbMergeConstMeta,
      argValues: [aabbLeftId, aabbRightId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbMergeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_merge",
        argNames: ["aabbLeftId", "aabbRightId"],
      );

  Future<void> aabbMergeWith(
      {required int aabbId, required int otherId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(aabbId);
    var arg1 = _platform.api2wire_u64(otherId);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_aabb_merge_with(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kAabbMergeWithConstMeta,
      argValues: [aabbId, otherId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAabbMergeWithConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "aabb_merge_with",
        argNames: ["aabbId", "otherId"],
      );

  int bvhNew({required Uint64List aabbs, dynamic hint}) {
    var arg0 = _platform.api2wire_uint_64_list(aabbs);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_bvh_new(arg0),
      parseSuccessData: _wire2api_u64,
      constMeta: kBvhNewConstMeta,
      argValues: [aabbs],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhNewConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_new",
        argNames: ["aabbs"],
      );

  Future<int> bvhNewAsync({required Uint64List aabbs, dynamic hint}) {
    var arg0 = _platform.api2wire_uint_64_list(aabbs);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_bvh_new_async(port_, arg0),
      parseSuccessData: _wire2api_u64,
      constMeta: kBvhNewAsyncConstMeta,
      argValues: [aabbs],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhNewAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_new_async",
        argNames: ["aabbs"],
      );

  void bvhDrop({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_bvh_drop(arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kBvhDropConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhDropConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_drop",
        argNames: ["bvhId"],
      );

  FlatBVH bvhFlatten({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_bvh_flatten(arg0),
      parseSuccessData: _wire2api_flat_bvh,
      constMeta: kBvhFlattenConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhFlattenConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_flatten",
        argNames: ["bvhId"],
      );

  Future<FlatBVH> bvhFlattenAsync({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_bvh_flatten_async(port_, arg0),
      parseSuccessData: _wire2api_flat_bvh,
      constMeta: kBvhFlattenAsyncConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhFlattenAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_flatten_async",
        argNames: ["bvhId"],
      );

  int bvhDepth({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_bvh_depth(arg0),
      parseSuccessData: _wire2api_u64,
      constMeta: kBvhDepthConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhDepthConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_depth",
        argNames: ["bvhId"],
      );

  Future<int> bvhDepthAsync({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_bvh_depth_async(port_, arg0),
      parseSuccessData: _wire2api_u64,
      constMeta: kBvhDepthAsyncConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhDepthAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_depth_async",
        argNames: ["bvhId"],
      );

  Uint64List bvhQueryAabbCollisions(
      {required int bvhId, required int aabbId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    var arg1 = _platform.api2wire_u64(aabbId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_bvh_query_aabb_collisions(arg0, arg1),
      parseSuccessData: _wire2api_uint_64_list,
      constMeta: kBvhQueryAabbCollisionsConstMeta,
      argValues: [bvhId, aabbId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhQueryAabbCollisionsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_query_aabb_collisions",
        argNames: ["bvhId", "aabbId"],
      );

  Uint64List bvhQueryPointCollisions(
      {required int bvhId,
      required double x,
      required double y,
      dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    var arg1 = api2wire_f64(x);
    var arg2 = api2wire_f64(y);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () =>
          _platform.inner.wire_bvh_query_point_collisions(arg0, arg1, arg2),
      parseSuccessData: _wire2api_uint_64_list,
      constMeta: kBvhQueryPointCollisionsConstMeta,
      argValues: [bvhId, x, y],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhQueryPointCollisionsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_query_point_collisions",
        argNames: ["bvhId", "x", "y"],
      );

  String bvhPrint({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_bvh_print(arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kBvhPrintConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhPrintConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_print",
        argNames: ["bvhId"],
      );

  Future<String> bvhPrintAsync({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_bvh_print_async(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kBvhPrintAsyncConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhPrintAsyncConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_print_async",
        argNames: ["bvhId"],
      );

  double bvhOverlapRatio({required int bvhId, dynamic hint}) {
    var arg0 = _platform.api2wire_u64(bvhId);
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_bvh_overlap_ratio(arg0),
      parseSuccessData: _wire2api_f64,
      constMeta: kBvhOverlapRatioConstMeta,
      argValues: [bvhId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBvhOverlapRatioConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bvh_overlap_ratio",
        argNames: ["bvhId"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  double _wire2api_f64(dynamic raw) {
    return raw as double;
  }

  FlatBVH _wire2api_flat_bvh(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlatBVH(
      minX: _wire2api_float_64_list(arr[0]),
      minY: _wire2api_float_64_list(arr[1]),
      maxX: _wire2api_float_64_list(arr[2]),
      maxY: _wire2api_float_64_list(arr[3]),
      depth: _wire2api_uint_64_list(arr[4]),
    );
  }

  Float64List _wire2api_float_64_list(dynamic raw) {
    return raw as Float64List;
  }

  int _wire2api_u64(dynamic raw) {
    return castInt(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint64List _wire2api_uint_64_list(dynamic raw) {
    return Uint64List.from(raw);
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
double api2wire_f64(double raw) {
  return raw;
}

// Section: finalizer
