[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutter_rust_bridge = { version = "1" }
generational-arena = { version = "0.2.8", features = ["std"] }
parry2d-f64 = "0.13.3"
ultraviolet = { version = "0.9.0", features = ["f64"] }

[lib]
crate-type = ["staticlib", "cdylib"]
