#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.69.0.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_say_hello_async_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "say_hello_async",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(say_hello_async()),
    )
}
fn wire_morton_codes_async_impl(
    port_: MessagePort,
    xs: impl Wire2Api<Vec<f64>> + UnwindSafe,
    ys: impl Wire2Api<Vec<f64>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "morton_codes_async",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_xs = xs.wire2api();
            let api_ys = ys.wire2api();
            move |task_callback| Ok(morton_codes_async(api_xs, api_ys))
        },
    )
}
fn wire_morton_codes_impl(
    xs: impl Wire2Api<Vec<f64>> + UnwindSafe,
    ys: impl Wire2Api<Vec<f64>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "morton_codes",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_xs = xs.wire2api();
            let api_ys = ys.wire2api();
            Ok(morton_codes(api_xs, api_ys))
        },
    )
}
fn wire_aabb_new_impl(
    min_x: impl Wire2Api<f64> + UnwindSafe,
    min_y: impl Wire2Api<f64> + UnwindSafe,
    max_x: impl Wire2Api<f64> + UnwindSafe,
    max_y: impl Wire2Api<f64> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_new",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_min_x = min_x.wire2api();
            let api_min_y = min_y.wire2api();
            let api_max_x = max_x.wire2api();
            let api_max_y = max_y.wire2api();
            Ok(aabb_new(api_min_x, api_min_y, api_max_x, api_max_y))
        },
    )
}
fn wire_aabb_new_bulk_impl(
    min_xs: impl Wire2Api<Vec<f64>> + UnwindSafe,
    min_ys: impl Wire2Api<Vec<f64>> + UnwindSafe,
    max_xs: impl Wire2Api<Vec<f64>> + UnwindSafe,
    max_ys: impl Wire2Api<Vec<f64>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_new_bulk",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_min_xs = min_xs.wire2api();
            let api_min_ys = min_ys.wire2api();
            let api_max_xs = max_xs.wire2api();
            let api_max_ys = max_ys.wire2api();
            Ok(aabb_new_bulk(
                api_min_xs, api_min_ys, api_max_xs, api_max_ys,
            ))
        },
    )
}
fn wire_aabb_new_bulk_benchmark_impl(
    min_xs: impl Wire2Api<Vec<f64>> + UnwindSafe,
    min_ys: impl Wire2Api<Vec<f64>> + UnwindSafe,
    max_xs: impl Wire2Api<Vec<f64>> + UnwindSafe,
    max_ys: impl Wire2Api<Vec<f64>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_new_bulk_benchmark",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_min_xs = min_xs.wire2api();
            let api_min_ys = min_ys.wire2api();
            let api_max_xs = max_xs.wire2api();
            let api_max_ys = max_ys.wire2api();
            Ok(aabb_new_bulk_benchmark(
                api_min_xs, api_min_ys, api_max_xs, api_max_ys,
            ))
        },
    )
}
fn wire_aabb_min_impl(
    aabb: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_min",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb = aabb.wire2api();
            Ok(aabb_min(api_aabb))
        },
    )
}
fn wire_aabb_max_impl(
    aabb: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_max",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb = aabb.wire2api();
            Ok(aabb_max(api_aabb))
        },
    )
}
fn wire_aabb_size_impl(
    aabb: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_size",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb = aabb.wire2api();
            Ok(aabb_size(api_aabb))
        },
    )
}
fn wire_aabb_center_impl(
    aabb: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_center",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb = aabb.wire2api();
            Ok(aabb_center(api_aabb))
        },
    )
}
fn wire_aabb_intersects_impl(
    aabb_left: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
    aabb_right: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_intersects",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb_left = aabb_left.wire2api();
            let api_aabb_right = aabb_right.wire2api();
            Ok(aabb_intersects(api_aabb_left, api_aabb_right))
        },
    )
}
fn wire_aabb_contains_impl(
    aabb: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
    point: impl Wire2Api<Vec<f64>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_contains",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb = aabb.wire2api();
            let api_point = point.wire2api();
            Ok(aabb_contains(api_aabb, api_point))
        },
    )
}
fn wire_aabb_contains_aabb_impl(
    aabb_left: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
    aabb_right: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_contains_aabb",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb_left = aabb_left.wire2api();
            let api_aabb_right = aabb_right.wire2api();
            Ok(aabb_contains_aabb(api_aabb_left, api_aabb_right))
        },
    )
}
fn wire_aabb_merge_impl(
    aabb_left: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
    aabb_right: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_merge",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb_left = aabb_left.wire2api();
            let api_aabb_right = aabb_right.wire2api();
            Ok(aabb_merge(api_aabb_left, api_aabb_right))
        },
    )
}
fn wire_aabb_merge_with_impl(
    aabb: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
    other: impl Wire2Api<RustOpaque<RwLock<AABB>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "aabb_merge_with",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabb = aabb.wire2api();
            let api_other = other.wire2api();
            Ok(aabb_merge_with(api_aabb, api_other))
        },
    )
}
fn wire_bvh_new_impl(
    aabbs: impl Wire2Api<Vec<RustOpaque<RwLock<AABB>>>> + UnwindSafe,
) -> support::WireSyncReturn {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync(
        WrapInfo {
            debug_name: "bvh_new",
            port: None,
            mode: FfiCallMode::Sync,
        },
        move || {
            let api_aabbs = aabbs.wire2api();
            Ok(bvh_new(api_aabbs))
        },
    )
}
fn wire_bvh_new_async_impl(
    port_: MessagePort,
    aabbs: impl Wire2Api<Vec<RustOpaque<RwLock<AABB>>>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "bvh_new_async",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_aabbs = aabbs.wire2api();
            move |task_callback| Ok(bvh_new_async(api_aabbs))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<f64> for f64 {
    fn wire2api(self) -> f64 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
#[path = "bridge_generated.web.rs"]
mod web;
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
